"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, Cpu, CircuitBoard, HardDrive, Wifi, Clock3, Download, Monitor, RefreshCw, ChevronRight, LogOut, ShieldCheck, X, FlaskConical } from "lucide-react";
import TrendChart from "./trend-chart";
import HardwareDetails from "./hardware-details";
import type { Sample, Row } from "./model";
type Device={name:string;lastReceived:number|null};
type Data={device:Device|null;latest:Sample|null;history:Row[]};
function demoData(hours:number):Data {const now=Date.now();const history=Array.from({length:100},(_,i)=>({t:now-(99-i)*hours*3600000/99,cpu:30+Math.sin(i*.27)*12+Math.sin(i*1.2)*7,memory:49+i*.07,gpu:57+Math.sin(i*.18)*20,cpuTemp:51+Math.sin(i*.27)*6,gpuTemp:62+Math.sin(i*.18)*5,netUp:.04,netDown:1.5+Math.sin(i*.3),gpuPowerW:125+Math.sin(i*.18)*55}));return {device:{name:"国内挂机电脑 · 演示",lastReceived:now},history,latest:{...history[99],memoryUsedGb:18,memoryTotalGb:32,gpuName:"示例显卡",cpuName:"示例八核处理器",motherboardName:"示例主板 X1",cpuTempSource:"LibreHardwareMonitor · CPU Package",memoryModules:[{name:"示例 DDR4 内存",capacityGb:16,speedMhz:3200},{name:"示例 DDR4 内存",capacityGb:16,speedMhz:3200}],storageModels:[{name:"示例 NVMe 固态硬盘",sizeGb:476},{name:"示例 SATA 硬盘",sizeGb:953}],gpuMemoryUsedGb:4.8,gpuMemoryTotalGb:12,gpuPowerW:124,cpuMhz:4200,uptimeSeconds:183540,diskRead:2.4,diskWrite:.6,disks:[{name:"C:",usedGb:182,totalGb:476},{name:"D:",usedGb:386,totalGb:953}]}};}
const fmt=(n:number|null|undefined,d=1)=>n==null?"—":n.toFixed(d);
export default function Dashboard({email}:{email:string}){
 const [demo,setDemo]=useState(false),[range,setRange]=useState(24),[data,setData]=useState<Data>({device:null,latest:null,history:[]}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[setup,setSetup]=useState(false),[busy,setBusy]=useState(false),[configReady,setConfigReady]=useState(false),[now,setNow]=useState(Date.now());
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/status?hours=${range}`,{cache:"no-store"});if(!r.ok)throw new Error(r.status===401?"登录已过期，请重新登录。":"暂时无法读取数据，请稍后重试。");setData(await r.json());setError("");}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[range]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},30000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!setup)return;const handler=(e:KeyboardEvent)=>{if(e.key==="Escape")setSetup(false);if(e.key==="Tab"){const items=Array.from(document.querySelectorAll<HTMLButtonElement|HTMLAnchorElement>('.modal button:not(:disabled),.modal a'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener("keydown",handler);document.querySelector<HTMLButtonElement>(".close")?.focus();return()=>document.removeEventListener("keydown",handler);},[setup]);
 const shown=demo?demoData(range):data,s=shown.latest;
 const current=useRef({demo,data:shown});current.current={demo,data:shown};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:"read_monitor_snapshot",description:"Read the currently displayed computer metrics, with an explicit demo-data flag. Does not change settings or create credentials.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object");const c=current.current;return {demo:c.demo,device:c.data.device,latest:c.data.latest};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const age=shown.device?.lastReceived?Math.max(0,now-shown.device.lastReceived):null,online=age!==null&&age<120000;
 async function connect(){setBusy(true);setError("");try{const r=await fetch("/api/device",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"国内挂机电脑"})});if(!r.ok)throw new Error("接入配置生成失败，请稍后重试。");const blob=new Blob([JSON.stringify(await r.json(),null,2)],{type:"application/json"});const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="config.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setConfigReady(true);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><div className="brand-icon"><Activity size={23}/></div><span>远程监控<small>REMOTE MONITOR</small></span></a><div className="nav-label">工作台</div><div className="nav-item active"><Monitor size={18}/>电脑概览<ChevronRight size={15}/></div><button className="nav-item" onClick={()=>setSetup(true)}><Download size={18}/>接入电脑</button><div className="sidebar-bottom"><ShieldCheck size={18}/><span>私人空间<small>数据仅登录后可见</small></span></div></aside><div className="workspace"><header><div className="breadcrumb">工作台 <span>/</span> <strong>电脑概览</strong></div><div className="account"><span title={email}>{email}</span><a href="/" onClick={async(e)=>{e.preventDefault();const r=await fetch("/api/logout",{method:"POST"});if(r.ok)location.assign("/");}} aria-label="退出登录"><LogOut size={17}/></a></div></header><main>
 <div className="heading"><div><p className="eyebrow">YOUR PC, AT A GLANCE</p><h1>电脑概览</h1><p className="muted">查看硬件状态，掌握每一次变化。</p></div><div className="actions"><button aria-pressed={demo} className={demo?"demo-button selected":"demo-button"} onClick={()=>setDemo(!demo)}><FlaskConical size={16}/>{demo?"退出演示":"查看演示"}</button><button className="primary" onClick={()=>setSetup(true)}>接入电脑 <ChevronRight size={16}/></button></div></div>
 {demo&&<div className="notice demo"><FlaskConical size={18}/><span><strong>演示模式</strong> · 所有数值均为模拟数据，不代表真实电脑状态。</span></div>}{error&&!demo&&<div className="notice error" role="alert">{error}<button onClick={()=>void refresh()}>重试</button></div>}
 <section className="device-strip"><div className="device-title"><div className="computer-icon"><Monitor size={25}/></div><div><h2>{shown.device?.name||"等待连接你的电脑"}</h2><span className="muted">{demo?"Windows · 示例设备":shown.device?"Windows · 私人设备":"在国内电脑运行采集程序后，数据会自动出现"}</span></div></div><div className="device-meta"><span className={`status ${online?"online":""}`}><i/>{demo?"模拟在线":loading&&!data.device?"正在读取":online?"正在上报":age===null?"尚未上报":"已停止上报"}</span><span className="muted">{shown.device?.lastReceived?`更新于 ${new Date(shown.device.lastReceived).toLocaleTimeString("zh-CN",{hour12:false})}`:"每 30 秒更新"}</span></div></section>
 {!demo&&age!==null&&!online&&<div className="notice">以下为最后一次上报的数据，已超过 {Math.floor(age/60000)} 分钟未更新。断网、关机或采集程序停止都可能导致此状态。</div>}
 <section className="cards"><MetricCard icon={<Cpu/>} name="CPU" value={fmt(s?.cpu)} unit="%" color="blue" sub={`温度 ${fmt(s?.cpuTemp)} °C · 频率 ${fmt(s?.cpuMhz,0)} MHz`}/><MetricCard icon={<CircuitBoard/>} name="内存" value={fmt(s?.memory)} unit="%" color="purple" sub={`${fmt(s?.memoryUsedGb)} / ${fmt(s?.memoryTotalGb)} GB`}/><MetricCard icon={<Activity/>} name="GPU" value={fmt(s?.gpu)} unit="%" color="teal" sub={`温度 ${fmt(s?.gpuTemp)} °C · 显存 ${fmt(s?.gpuMemoryUsedGb)} GB`}/><MetricCard icon={<Wifi/>} name="网络下载" value={fmt(s?.netDown,2)} unit="MB/s" color="orange" sub={`上传 ${fmt(s?.netUp,2)} MB/s`}/></section>
 <TrendChart history={shown.history} range={range} setRange={setRange} demo={demo} loading={loading} refresh={()=>void refresh()} showDemo={()=>setDemo(true)}/>
 <div className="details-grid"><section className="panel"><div className="panel-head"><h2><HardDrive size={18}/>磁盘空间</h2><span className="muted">已用 / 总容量</span></div>{s?.disks?.length?s.disks.map(d=><div className="disk" key={d.name}><div><strong>{d.name}</strong><span>{fmt(d.usedGb,0)} / {fmt(d.totalGb,0)} GB</span></div><div className="track"><i style={{width:`${Math.min(100,d.usedGb/d.totalGb*100)}%`}}/></div></div>):<p className="empty-small">接入后显示各磁盘容量</p>}<div className="disk-rates"><span>读取 <strong>{fmt(s?.diskRead)} MB/s</strong></span><span>写入 <strong>{fmt(s?.diskWrite)} MB/s</strong></span></div></section><section className="panel"><div className="panel-head"><h2><Clock3 size={18}/>运行详情</h2></div><dl><div><dt>连续运行</dt><dd>{s?.uptimeSeconds!=null?`${Math.floor(s.uptimeSeconds/86400)} 天 ${Math.floor(s.uptimeSeconds%86400/3600)} 小时`:"—"}</dd></div><div><dt>显卡</dt><dd>{s?.gpuName||"—"}</dd></div><div><dt>显卡功耗</dt><dd>{fmt(s?.gpuPowerW)} W</dd></div><div><dt>脚本任务进度</dt><dd>尚未接入</dd></div></dl></section></div><HardwareDetails sample={s}/><footer><span>未读取到的指标显示为「—」，不按 0 计算。电脑在线不代表脚本任务正常。</span><span>历史保留 30 天</span></footer></main></div>
 {setup&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setSetup(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="setup-title"><button className="close" aria-label="关闭" onClick={()=>setSetup(false)}><X/></button><p className="eyebrow">CONNECT YOUR PC</p><h2 id="setup-title">接入国内挂机电脑</h2><p className="muted">只在被监控电脑运行。手机和其他电脑无需安装。</p><ol className="steps"><li><strong>下载 Windows 采集包</strong><p>解压到固定文件夹，采集程序只读取硬件状态。</p><a className="button" href="/collector.zip" download>下载采集包 <Download size={16}/></a></li><li><strong>生成并下载接入配置</strong><p>将 config.json 放入刚才解压的文件夹。配置含密钥，请勿分享。重新生成会立即使旧配置失效。</p><button className="primary" disabled={busy} onClick={()=>void connect()}>{busy?"正在生成…":configReady?"重新生成配置":"下载接入配置"}</button>{configReady&&<p className="success" role="status">配置已生成，请保存到采集包文件夹。</p>}</li><li><strong>双击「启动监控.vbs」</strong><p>在小窗口中导入配置并开始采集，看到“上报成功”后可最小化到托盘。接入后退出演示即可查看真实数据。</p></li></ol><p className="setup-note">基础采集支持 Windows 10/11。NVIDIA 显卡优先使用驱动附带的工具；其他显卡与温度可选用 LibreHardwareMonitor，详情见采集包说明。超过 2 分钟未上报会标记离线；本版不发送通知。</p>{error&&<p className="error-text" role="alert">{error}</p>}</section></div>}
 </div>;
}
function MetricCard({icon,name,value,unit,sub,color}:{icon:React.ReactNode;name:string;value:string;unit:string;sub:string;color:string}){return <article className={`metric-card ${color}`}><div className="metric-label"><span>{name}</span>{icon}</div><div className="metric-value">{value}<small>{unit}</small></div><p>{sub}</p></article>}
