"use client";
import {useCallback, useEffect, useRef, useState} from 'react';
import type {ReactNode} from 'react';
import {Activity, Cpu, CircuitBoard, HardDrive, Wifi, Clock3, Download, Monitor, RefreshCw, ChevronRight, LogOut, ShieldCheck, X, FlaskConical, Workflow} from 'lucide-react';
import TrendChart from './trend-chart';
import HardwareDetails from './hardware-details';
import {LanguageSwitch, useLanguage} from './language';
import type {AutoMas, Sample, Row} from './model';

type Device={name:string;lastReceived:number|null};
type Data={device:Device|null;latest:Sample|null;history:Row[]};
function demoData(hours:number):Data {
 const now=Date.now();
 const history=Array.from({length:100},(_,i)=>({t:now-(99-i)*hours*3600000/99,cpu:30+Math.sin(i*.27)*12+Math.sin(i*1.2)*7,memory:49+i*.07,gpu:57+Math.sin(i*.18)*20,cpuTemp:51+Math.sin(i*.27)*6,gpuTemp:62+Math.sin(i*.18)*5,netUp:.04,netDown:1.5+Math.sin(i*.3),gpuPowerW:125+Math.sin(i*.18)*55}));
 return {device:{name:'Demo PC',lastReceived:now},history,latest:{...history[99],memoryUsedGb:18,memoryTotalGb:32,gpuName:'Example GPU',cpuName:'Example eight-core CPU',motherboardName:'Example motherboard X1',cpuTempSource:'LibreHardwareMonitor · CPU Package',memoryModules:[{name:'Example DDR4 RAM',capacityGb:16,speedMhz:3200}],storageModels:[{name:'Example NVMe SSD',sizeGb:476}],gpuMemoryUsedGb:4.8,gpuMemoryTotalGb:12,gpuPowerW:124,cpuMhz:4200,uptimeSeconds:183540,diskRead:2.4,diskWrite:.6,disks:[{name:'C:',usedGb:182,totalGb:476}],autoMas:{state:'ready',version:'5.4',activeTasks:1,scheduledCount:2,lastResultAt:'2026-09-28 01:00:00',lastResult:'DONE',tasks:[{mode:'AutoProxy',stopping:false,scripts:[{name:'Example task',status:'running'}]}]}}};
}
const fmt=(n:number|null|undefined,d=1)=>n==null?'—':n.toFixed(d);

export default function Dashboard({email}:{email:string}){
 const {tr,locale}=useLanguage();
 const [demo,setDemo]=useState(false),[range,setRange]=useState(24),[data,setData]=useState<Data>({device:null,latest:null,history:[]}),[error,setError]=useState<'expired'|'read'|'connect'|''>(''),[loading,setLoading]=useState(true),[setup,setSetup]=useState(false),[busy,setBusy]=useState(false),[configReady,setConfigReady]=useState(false),[now,setNow]=useState(Date.now());
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/status?hours=${range}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'expired':'read');setData(await r.json());setError('')}catch(e){setError(e instanceof Error&&e.message==='expired'?'expired':'read')}finally{setLoading(false)}},[range]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh()},30000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!setup)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setSetup(false);if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLButtonElement|HTMLAnchorElement>('.modal button:not(:disabled),.modal a'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);document.querySelector<HTMLButtonElement>('.close')?.focus();return()=>document.removeEventListener('keydown',handler)},[setup]);
 const shown=demo?demoData(range):data,s=shown.latest;
 const current=useRef({demo,data:shown});current.current={demo,data:shown};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_monitor_snapshot',description:'Read currently displayed computer and AUTO-MAS summary metrics, with a demo-data flag. No settings or credentials are changed.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');const c=current.current;return {demo:c.demo,device:c.data.device,latest:c.data.latest}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const age=shown.device?.lastReceived?Math.max(0,now-shown.device.lastReceived):null,online=age!==null&&age<120000;
 async function connect(){setBusy(true);setError('');try{const r=await fetch('/api/device',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Monitored PC'})});if(!r.ok)throw new Error();const blob=new Blob([JSON.stringify(await r.json(),null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='config.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setConfigReady(true);await refresh()}catch{setError('connect')}finally{setBusy(false)}}
 const messages={expired:tr('登录已过期，请重新登录。','Your session expired. Please sign in again.'),read:tr('暂时无法读取数据，请稍后重试。','Could not load data. Please retry.'),connect:tr('接入配置生成失败，请稍后重试。','Could not create the connection file. Please retry.')};
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><div className="brand-icon"><Activity size={23}/></div><span>{tr('远程监控','Remote Monitor')}<small>REMOTE MONITOR</small></span></a><div className="nav-label">{tr('工作台','WORKSPACE')}</div><div className="nav-item active"><Monitor size={18}/>{tr('电脑概览','Overview')}<ChevronRight size={15}/></div><button className="nav-item" onClick={()=>setSetup(true)}><Download size={18}/>{tr('接入电脑','Connect PC')}</button><div className="sidebar-bottom"><ShieldCheck size={18}/><span>{tr('私人空间','Private space')}<small>{tr('数据仅登录后可见','Sign-in required')}</small></span></div></aside><div className="workspace"><header><div className="breadcrumb">{tr('工作台','Workspace')} <span>/</span> <strong>{tr('电脑概览','Overview')}</strong></div><div className="account"><LanguageSwitch/><span title={email}>{email}</span><a href="/" onClick={async(e)=>{e.preventDefault();const r=await fetch('/api/logout',{method:'POST'});if(r.ok)location.assign('/')}} aria-label={tr('退出登录','Sign out')}><LogOut size={17}/></a></div></header><main>
 <div className="heading"><div><p className="eyebrow">YOUR PC, AT A GLANCE</p><h1>{tr('电脑概览','Computer overview')}</h1><p className="muted">{tr('硬件状态、自动化任务与历史趋势，一处查看。','Hardware, automation tasks and history in one place.')}</p></div><div className="actions"><button aria-pressed={demo} className={demo?'demo-button selected':'demo-button'} onClick={()=>setDemo(!demo)}><FlaskConical size={16}/>{demo?tr('退出演示','Exit demo'):tr('查看演示','View demo')}</button><button className="primary" onClick={()=>setSetup(true)}>{tr('接入电脑','Connect PC')} <ChevronRight size={16}/></button></div></div>
 {demo&&<div className="notice demo"><FlaskConical size={18}/><span><strong>{tr('演示模式','Demo mode')}</strong> · {tr('所有数值均为模拟数据，不代表真实电脑状态。','All values are simulated and do not represent a real computer.')}</span></div>}{error&&!demo&&<div className="notice error" role="alert">{messages[error]}<button onClick={()=>void refresh()}>{tr('重试','Retry')}</button></div>}
 <section className="device-strip"><div className="device-title"><div className="computer-icon"><Monitor size={25}/></div><div><h2>{shown.device?.name||tr('等待连接你的电脑','Waiting for your computer')}</h2><span className="muted">{demo?tr('Windows · 示例设备','Windows · demo device'):shown.device?tr('Windows · 私人设备','Windows · private device'):tr('运行 Windows 采集程序后，这里会自动显示数据','Run the Windows collector to see data here')}</span></div></div><div className="device-meta"><span className={`status ${online?'online':''}`}><i/>{demo?tr('模拟在线','Demo online'):loading&&!data.device?tr('正在读取','Loading'):online?tr('正在上报','Reporting'):age===null?tr('尚未上报','No report yet'):tr('已停止上报','Not reporting')}</span><span className="muted">{shown.device?.lastReceived?`${tr('更新于','Updated')} ${new Date(shown.device.lastReceived).toLocaleTimeString(locale,{hour12:false})}`:tr('约每 30 秒更新','Updates about every 30 seconds')}</span></div></section>
 {!demo&&age!==null&&!online&&<div className="notice">{tr(`以下为最后一次上报的数据，已超过 ${Math.floor(age/60000)} 分钟未更新。断网、关机或采集程序停止都可能导致此状态。`,`Last reported data is shown. No update for ${Math.floor(age/60000)} minutes; the PC, network or collector may be offline.`)}</div>}
 <section className="cards"><MetricCard icon={<Cpu/>} name="CPU" value={fmt(s?.cpu)} unit="%" color="blue" sub={`${tr('温度','Temp')} ${fmt(s?.cpuTemp)} °C · ${tr('频率','Clock')} ${fmt(s?.cpuMhz,0)} MHz`}/><MetricCard icon={<CircuitBoard/>} name={tr('内存','Memory')} value={fmt(s?.memory)} unit="%" color="purple" sub={`${fmt(s?.memoryUsedGb)} / ${fmt(s?.memoryTotalGb)} GB`}/><MetricCard icon={<Activity/>} name="GPU" value={fmt(s?.gpu)} unit="%" color="teal" sub={`${tr('温度','Temp')} ${fmt(s?.gpuTemp)} °C · ${tr('显存','VRAM')} ${fmt(s?.gpuMemoryUsedGb)} GB`}/><MetricCard icon={<Wifi/>} name={tr('网络下载','Download')} value={fmt(s?.netDown,2)} unit="MB/s" color="orange" sub={`${tr('上传','Upload')} ${fmt(s?.netUp,2)} MB/s`}/></section>
 <AutoMasPanel value={s?.autoMas} online={online} demo={demo}/>
 <TrendChart history={shown.history} range={range} setRange={setRange} demo={demo} loading={loading} refresh={()=>void refresh()} showDemo={()=>setDemo(true)}/>
 <div className="details-grid"><section className="panel"><div className="panel-head"><h2><HardDrive size={18}/>{tr('磁盘空间','Disk space')}</h2><span className="muted">{tr('已用 / 总容量','Used / total')}</span></div>{s?.disks?.length?s.disks.map(d=><div className="disk" key={d.name}><div><strong>{d.name}</strong><span>{fmt(d.usedGb,0)} / {fmt(d.totalGb,0)} GB</span></div><div className="track"><i style={{width:`${Math.min(100,d.usedGb/d.totalGb*100)}%`}}/></div></div>):<p className="empty-small">{tr('接入后显示各磁盘容量','Disk capacities appear after connecting')}</p>}<div className="disk-rates"><span>{tr('读取','Read')} <strong>{fmt(s?.diskRead)} MB/s</strong></span><span>{tr('写入','Write')} <strong>{fmt(s?.diskWrite)} MB/s</strong></span></div></section><section className="panel"><div className="panel-head"><h2><Clock3 size={18}/>{tr('运行详情','System details')}</h2></div><dl><div><dt>{tr('连续运行','Uptime')}</dt><dd>{s?.uptimeSeconds!=null?tr(`${Math.floor(s.uptimeSeconds/86400)} 天 ${Math.floor(s.uptimeSeconds%86400/3600)} 小时`,`${Math.floor(s.uptimeSeconds/86400)} d ${Math.floor(s.uptimeSeconds%86400/3600)} h`):'—'}</dd></div><div><dt>{tr('显卡','Graphics card')}</dt><dd>{s?.gpuName||'—'}</dd></div><div><dt>{tr('显卡功耗','GPU power')}</dt><dd>{fmt(s?.gpuPowerW)} W</dd></div></dl></section></div><HardwareDetails sample={s}/><footer><span>{tr('未读取到的指标显示为「—」，不按 0 计算。电脑在线不代表脚本任务正常。','Unavailable metrics show “—”, not zero. A reporting PC does not prove automation tasks are healthy.')}</span><span>{tr('历史保留 30 天','30-day history')}</span></footer></main></div>
 {setup&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setSetup(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="setup-title"><button className="close" aria-label={tr('关闭','Close')} onClick={()=>setSetup(false)}><X/></button><p className="eyebrow">CONNECT YOUR PC</p><h2 id="setup-title">{tr('接入 Windows 电脑','Connect a Windows PC')}</h2><p className="muted">{tr('只在被监控电脑运行。手机和其他电脑无需安装。','Run this only on the PC you want to monitor. Other devices need no installation.')}</p><ol className="steps"><li><strong>{tr('下载 Windows 采集包','Download the Windows collector')}</strong><p>{tr('解压到固定文件夹。采集程序只读取状态，不控制电脑。','Extract to a permanent folder. It reads status and does not control the PC.')}</p><a className="button" href="/collector.zip" download>{tr('下载采集包','Download collector')} <Download size={16}/></a></li><li><strong>{tr('生成并下载接入配置','Generate a connection file')}</strong><p>{tr('将 config.json 放入解压的文件夹。它含有密钥，请勿分享；重新生成会使旧配置失效。','Put config.json in that folder. It contains a secret: do not share it. Regenerating it revokes the old file.')}</p><button className="primary" disabled={busy} onClick={()=>void connect()}>{busy?tr('正在生成…','Generating…'):configReady?tr('重新生成配置','Regenerate file'):tr('下载接入配置','Download connection file')}</button>{configReady&&<p className="success" role="status">{tr('配置已生成，请保存到采集包文件夹。','Save the downloaded file in the collector folder.')}</p>}</li><li><strong>{tr('双击「启动监控.vbs」','Run 启动监控.vbs')}</strong><p>{tr('在窗口中导入配置并开始采集。看到“上报成功”后可最小化到托盘。','Import the file in the collector window. After “Upload succeeded”, minimize it to the tray.')}</p></li></ol><p className="setup-note">{tr('支持 Windows 10/11。NVIDIA 数据使用驱动工具；CPU 温度可选择已有的 LibreHardwareMonitor。AUTO-MAS 状态通过本机只读接口采集，无需远程开放端口。','Supports Windows 10/11. NVIDIA data uses the driver utility; CPU temperature optionally uses LibreHardwareMonitor. AUTO-MAS status comes from its local read-only API; do not open its port externally.')}</p>{error&&<p className="error-text" role="alert">{messages[error]}</p>}</section></div>}
 </div>;
}
function MetricCard({icon,name,value,unit,sub,color}:{icon:ReactNode;name:string;value:string;unit:string;sub:string;color:string}){return <article className={`metric-card ${color}`}><div className="metric-label"><span>{name}</span>{icon}</div><div className="metric-value">{value}<small>{unit}</small></div><p>{sub}</p></article>}
function AutoMasPanel({value,online,demo}:{value:AutoMas|null|undefined;online:boolean;demo:boolean}){
 const {tr}=useLanguage();
 const active=demo||online;
 const state=!active?'offline':value?.state||'unavailable';
 const status=state==='ready'?tr('任务快照可用','Task snapshot available'):state==='limited'?tr('历史模式','History only'):state==='starting'?tr('正在启动','Starting'):state==='unsupported'?tr('版本不支持','Unsupported version'):state==='offline'?tr('电脑离线','PC offline'):tr('未连接','Cannot connect');
 return <section className="panel automas-panel">
  <div className="panel-head"><div><h2><Workflow size={18}/>AUTO-MAS</h2><p className="muted">{tr('仅上报任务摘要（含脚本名）；不上传原始日志、账号或完整配置','Only task summaries (including script names) are uploaded; no raw logs, accounts or full configuration')}</p></div><span className={`status ${state==='ready'||state==='limited'?'online':''}`}><i/>{status}</span></div>
  <div className="automas-body">
   {(state==='ready'||state==='limited')&&<>
    <div className="automas-stats">{state==='ready'&&<><div><strong>{value?.activeTasks??0}</strong><span>{tr('运行中任务','Active tasks')}</span></div><div><strong>{value?.scheduledCount??0}</strong><span>{tr('已安排脚本','Scheduled scripts')}</span></div></>}{value?.version&&<div><strong>{value.version}</strong><span>{tr('AUTO-MAS 版本','AUTO-MAS version')}</span></div>}</div>
    {value?.lastResultAt&&<p className="last-result">{tr('最近历史记录','Latest recorded result')} · <strong>{value.lastResult==='DONE'?tr('完成','Done'):tr('报错','Error')}</strong> · {value.lastResultAt}</p>}
    {state==='limited'?<p className="automas-empty">{tr('此版本没有运行快照接口，只能显示后端在线和历史结果；无法判断当前任务是否运行。','This version has no runtime snapshot API. Only backend availability and historical results are shown; current task activity is unknown.')}</p>:value?.tasks?.length?<div className="task-list">{value.tasks.map((task,i)=><div className="task-row" key={i}><span className="task-index">{String(i+1).padStart(2,'0')}</span><div><strong>{task.stopping?tr('正在停止','Stopping'):task.mode==='AutoProxy'?tr('自动代理','Auto proxy'):task.mode==='ScriptConfig'?tr('脚本配置','Script config'):tr('更新任务','Update task')}</strong><small>{task.scripts.length?task.scripts.map(s=>`${s.name||tr('未命名脚本','Unnamed script')} · ${s.status||'—'}`).join(' / '):tr('等待脚本状态','Waiting for script status')}</small></div></div>)}</div>:<p className="automas-empty">{tr('当前没有运行中的任务。已安排脚本数不代表任务正在执行。','No task is currently running. Scheduled scripts are not active tasks.')}</p>}
   </>}
   {state!=='ready'&&state!=='limited'&&<p className="automas-empty">{state==='offline'?tr('最后一次 AUTO-MAS 状态可能已过期，请先恢复采集端上报。','The last AUTO-MAS status may be stale. Restore collector reporting first.'):state==='unsupported'?tr('本机 AUTO-MAS 没有可用的只读接口。','This AUTO-MAS version has no supported read-only API.'):tr('采集端尚未读到 AUTO-MAS 本机接口。请确认程序已启动，且本机端口配置正确。','The collector cannot read the local AUTO-MAS API. Check that it is running and the local port is correct.')}</p>}
  </div>
  <p className="automas-foot">{tr('后端在线和历史“完成”均不代表当前脚本正在推进；本版不监测任务卡死。','Backend availability and a historical “Done” do not prove a current task is progressing; stalled tasks are not detected.')}</p>
 </section>;
}
