import {Activity, ShieldCheck} from 'lucide-react';
import {ResponsiveContainer, AreaChart, Area, CartesianGrid, XAxis, YAxis, Tooltip} from 'recharts';
import type {Row,Sample} from './model';
import {useLanguage} from './language';

type Metric='healthScore'|'stabilityIndex';
function ScoreChart({history,metric,max,color,title}:{history:Row[];metric:Metric;max:number;color:string;title:string}){
 const {tr,locale}=useLanguage();
 const hasData=history.some(row=>row[metric]!=null);
 return <article className="health-plot"><h3>{title}</h3><div className="health-chart">{hasData?<ResponsiveContainer width="100%" height="100%"><AreaChart data={history} margin={{top:10,right:14,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#304057" strokeDasharray="4 5"/><XAxis dataKey="t" type="number" domain={["dataMin","dataMax"]} tickFormatter={value=>new Date(value).toLocaleString(locale,{hour:'2-digit',minute:'2-digit',month:'numeric',day:'numeric'})} minTickGap={40} tick={{fill:'#9aabc1',fontSize:11}} tickLine={false} axisLine={false}/><YAxis domain={[0,max]} width={36} tick={{fill:'#9aabc1',fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:'#172233',border:'1px solid #39485d',borderRadius:10,color:'#edf3fd'}} labelFormatter={value=>new Date(Number(value)).toLocaleString(locale)} formatter={value=>[`${Number(value).toFixed(1)} / ${max}`,title]}/><Area dataKey={metric} type="linear" stroke={color} fill={color} fillOpacity={.12} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<p className="health-empty">{tr('等待新版采集端上报此指标','Waiting for the updated collector to report this metric')}</p>}</div></article>;
}
export default function HealthPanel({sample,history,online,demo,range,setRange}:{sample:Sample|null;history:Row[];online:boolean;demo:boolean;range:number;setRange:(hours:number)=>void}){
 const {tr}=useLanguage();
 const number=(value:number|null|undefined,d=1)=>value==null?'—':value.toFixed(d);
 const displaySample=demo&&sample?{...sample,healthCoverage:100,wheaEvents24h:0,memoryEvents24h:0}:sample;
 return <div className="health-module"><div className="health-range"><span>{tr('历史范围','History range')}</span><div className="segmented">{[1,24,168].map(hours=><button key={hours} aria-pressed={range===hours} className={range===hours?'selected':''} onClick={()=>setRange(hours)}>{hours===168?tr('7 天','7 days'):tr(`${hours} 小时`,`${hours} hour${hours===1?'':'s'}`)}</button>)}</div></div><div className="health-scores"><article className="panel health-score"><div className="health-score-title"><Activity size={20}/>{tr('系统健康指数','System health index')}</div><strong>{number(displaySample?.healthScore)}<small> / 100</small></strong><p>{tr('当前资源压力的启发式评分；不是硬件诊断。','A heuristic score for current resource pressure, not a hardware diagnosis.')}</p><small>{tr('已获取指标权重','Available signal coverage')}：{number(displaySample?.healthCoverage,0)}%</small></article><article className="panel health-score"><div className="health-score-title"><ShieldCheck size={20}/>{tr('系统稳定指数','System stability index')}</div><strong>{number(displaySample?.stabilityIndex)}<small> / 10</small></strong><p>{tr('直接读取 Windows 可靠性监视器指数，通常按日更新。','Read directly from the Windows Reliability Monitor; usually updated daily.')}</p><small>{displaySample?.stabilityIndex==null?tr('Windows 未提供此指标','Unavailable from Windows'):tr('来源：Win32_ReliabilityStabilityMetrics','Source: Win32_ReliabilityStabilityMetrics')}</small></article></div><div className="health-plots"><ScoreChart history={history} metric="healthScore" max={100} color="#62b6ff" title={tr('健康指数历史','Health index history')}/><ScoreChart history={history} metric="stabilityIndex" max={10} color="#62dbc0" title={tr('稳定指数历史','Stability index history')}/></div><section className="panel health-events"><h2>{tr('Windows 硬件错误记录','Windows hardware error records')}</h2><div><span>{tr('近 24 小时 WHEA 事件','WHEA events, last 24 hours')}</span><strong>{displaySample?.wheaEvents24h==null?'—':`${sample.wheaEvents24h}${sample.wheaEventsCapped?'+':''}`}</strong></div><div><span>{tr('其中明确标为内存相关','Explicitly classified as memory related')}</span><strong>{displaySample?.memoryEvents24h==null?'—':`${sample.memoryEvents24h}${sample.wheaEventsCapped?'+':''}`}</strong></div><p>{tr('只统计 Windows 已记录且可识别的事件。普通非 ECC 内存无法提供完整纠错计数；0 条不等于内存无故障。系统离线时显示的是上次结果。','Only Windows-recorded, recognizable events are counted. Consumer non-ECC RAM cannot provide a complete correction count; zero events does not prove error-free memory. Offline values are from the last report.')}</p></section>{!online&&!demo&&<p className="health-stale">{tr('电脑当前未上报，评分和错误计数可能已经过期。','The PC is not reporting; scores and event counts may be stale.')}</p>}</div>;
}
